test.view:
  path: "test"
  controller: Test
  action: Default
  method: [GET]

test.edit:
  path: "test/{var1}/edit/{var2}"
  controller: Test
  action: Edit
  method: [GET, POST]
  params:
    var1: "\\w+"
    var2: "[1-5]"